---
title: "PlotsForFinal"
author: "Anchors"
date: "2023-03-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Plot A

```{r}
ben=read.csv("benfords.csv")

library(ggplot2)
base= ggplot(data = ben,
             aes(x = digit,
                 y = perc))
ben1 = base + geom_bar(fill ="purple",
                        stat = 'identity') 

titleText='Expected Frequency of Each Digit Appearing First in Data'
subtext='How often will each digit be the leading digit according to Benford?'
sourceText='Source: Benfords Law'
ben2 = ben1 + labs(title=titleText,subtitle = subtext,
                     x = 'First Digit',
                     y = 'Frequency',
                     caption = sourceText)

ben3 = ben2 ##+ geom_hline(yintercept = 11.11, #where
                      ##   linetype="dashed",
                        ## size=1.5, #thickness
                        ## alpha=0.1) #transparency

library(scales) # for "unit_format""

# customize Y axis
ben4 = ben3 + scale_y_continuous(breaks=c(0,5,10,15,20,25,30,35),
                                   limits = c(0, 35),
                                   labels=unit_format(suffix = '%'))

paste0(round(ben$perc,2), '%')

LABELS=paste0(round(ben$perc,2), '%')
###
ben5 = ben4 + geom_text(vjust=0, #hjust if flipping
                          size = 3,
                          aes(y = perc ,
                              label = LABELS))

ben$digit <- as.factor(ben$digit)

ben6 = ben5 + theme_classic()

ben7 = ben6 + theme(
  panel.background = element_rect(fill = "lightyellow")
  )

ben8 = ben7 + theme(plot.caption = element_text(hjust = 0),
                      plot.title = element_text(hjust = 0.5),
                      plot.subtitle = element_text(hjust = 0.5))
ben8
```

```{r save-BenfordsLaw, echo=FALSE}
#saving plot
saveRDS(ben8, file = "BenfordsLaw.rds")
```

Plot B

```{r}
library(readxl)
council=read_xlsx("CouncilAge.xlsx")

library(ggplot2)
base= ggplot(data = council,
             aes(x = Councilmember,
                 y = Age))
plot1 = base +  geom_segment(aes(x = Councilmember, xend = Councilmember, y = Age, yend = 35),  color="darkgrey")+
  geom_point(size=3, color="green") +
               ylim(30,70)

titleText='Ages of Seattle City Councilmembers'
subtext='How old are our elected officials?'
sourceText='Source: Wikipedia'
plot2 = plot1 + labs(title=titleText, subtitle = subtext,
                     caption = sourceText)

plot3 = plot2 + theme_classic()

plot4 = plot3 + coord_flip()

plot5 = plot4 + geom_hline(yintercept = 35, 
                           linetype="dashed", 
                           size=1, 
                           alpha=0.3)

plot6 = plot5 +  annotate(
  "text", label = "Median Age \n in Seattle",
  x = 8.5, y = 32.3, size = 2.2, color = "black"
)


plot7 = plot6 + theme(plot.title = element_text(hjust = 0.5),
                      plot.subtitle = element_text(hjust = 0.5),
                      axis.title.y = element_blank())
plot7
```

```{r save-CityCouncilAge, echo=FALSE}
#saving plot
saveRDS(plot7, file = "CityCouncilAge.rds")
```

Plot C

```{r}

read.csv("Copy of best-states-to-work-index-2022.csv")
work_index <- read.csv("Copy of best-states-to-work-index-2022.csv")
work_index3 <- work_index[ , c(1,2,5:7)]

dist_in_work=dist(work_index3[,-c(1,2)])

library(scales)

library(usmap)
library(cluster)
cluster= cluster::pam(x=dist_in_work,
              k = 4, cluster.only = F)
work_index3$cluster <- cluster$clustering

work_index3$state <- work_index3$State

work_index$state <- work_index$State

work_index3$cluster <- as.factor(work_index3$cluster)

subtext="Where 1 Indicates Worst for Workers, and 4 is the Best"

library(ggplot2)

plot_usmap(data = work_index3, values = "cluster",na.rm=TRUE, color="azure4")+scale_fill_brewer(palette='RdYlBu')+ labs(title = "Best States to Work on a Scale of 1 to 4",subtitle = subtext)+ theme(legend.title=element_blank())

work1 <- plot_usmap(data = work_index3, values = "cluster",na.rm=TRUE, color="azure4")+ scale_fill_brewer(palette='RdYlBu')+ labs(title = "Best States to Work on a Scale of 1 to 4",subtitle = subtext)+ theme(legend.title=element_blank())

##Final Map
work2=work1+theme(plot.title = element_text(hjust = .5,face="bold",size = 14),plot.subtitle = element_text(hjust = .5,face="italic"))
work2
```

```{r save-USWorkMap, echo=FALSE}
#saving plot
saveRDS(work2, file = "USWorkMap.rds")
```

